/* $Revision: 1.1 $ */
// Read_ADC.cpp
// Automatically generated by Matlab AppWizard version 1.0
//
// This is the gateway routine for a MATLAB Math/Graphics Library-based
// C MATLAB MEX File.

/*for all programs that use Son.H, need to include
//Windows.H and Windef.h*/
#include <windows.h>
#include <windef.h>

#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>

//header files for ced libraries

#include "SON.H"
#include "SONINTL.H"

#include <mex.h>
#include <matrix.h>

int countADCpts(int hand, int adcchan, long *MaxTime)
{
	int ticks, StartTime;

	int np;

	short data[1000];
	short *dataptr;
	
	long numpts;
	
	TSTime pbTime;

	dataptr = data;


	adcchan = 0;
	
	*MaxTime = SONChanMaxTime(hand, adcchan);

	np = 1000;
	numpts = 0;

	ticks=SONChanDivide(hand, adcchan);
	StartTime = 0;

	while (StartTime<*MaxTime)
	{
		np = SONGetADCData(hand, adcchan, dataptr, 1000, StartTime, *MaxTime, &pbTime, NULL);
		StartTime =pbTime + np*ticks;
		numpts+=np;
	}



	(*MaxTime) = (*MaxTime)/ticks;
	
	return numpts;

}

void readADCdata(int hand, long numpts, int adcchan, int *x, long MaxTime)
{
	/*------------------------------------------------------
	Logic:  take in a handle to a CED file
	read in the ADC data
	but since SONGetADCdata only reads in chunks of continuous
	ADC data, we need to place all the seperate chunks of data
	into one array.
	------------------------------------------------------*/
	int i, ticks, StartTime, counter, StartCounter;
	long np, num_pts_read;

	short *data;
	short *dataptr;

	TSTime pbTime;


	//initialize an temp array to hold numpts worth of data
	data = (short *)calloc(numpts, sizeof(short));

	dataptr = data;
	
	//set the channel to be read from
	adcchan = 0;
	
	//read in the maximum time
	MaxTime = SONChanMaxTime(hand, adcchan);

	np = 1;

	//find the number of microsecs per adc data point
	ticks=SONChanDivide(hand, adcchan);
	StartTime = 0;

	//counter variables to be used within the for loop
	StartCounter = 0;
	num_pts_read = 0;

	//while the number of points read is less than the total number of pts
	while (num_pts_read < numpts)
	{
		np = SONGetADCData(hand, adcchan, dataptr, numpts, StartTime, MaxTime, &pbTime, NULL);

		//advance the starting point for data acquisition by the appropriate increment
		StartTime=pbTime + np*ticks;

		//insert data into output array
		counter = 0;
		StartCounter = pbTime/ticks;
		for (i=StartCounter;i<StartCounter+np; i++)
		{
			x[i] = data[counter];
			counter++;
		}
		num_pts_read +=np;

	}

	free((short *)data);
	data = NULL;

}

void mexFunction(
	int nlhs,              // Number of left hand side (output) arguments
	mxArray *plhs[],       // Array of left hand side arguments
	int nrhs,              // Number of right hand side (input) arguments
	const mxArray *prhs[]  // Array of right hand side arguments
)
{
	long numpts;
	int dims[2];
	double *ADCdata;
	long MaxTime;
	long ChanDur;
	int hand;
	int flag;
	char *path;
	char *filename;
	char *path_filename;

	path = mxArrayToString(prhs[0]);
	filename = mxArrayToString(prhs[1]);

	path_filename = path;
	strcat(path_filename, filename);


	//open the CED data file
	hand = SONOpenOldFile(path_filename, 1);

	/*------------------------------------------------------
	Reading in ADC data here
	------------------------------------------------------*/

	//read in the number of pts in the ADC channel
	mexPrintf("Reading in Number of pts.\n");

	numpts = countADCpts(hand, 0, &ChanDur);

	mexPrintf("Number of ADC Points = %d\n", numpts);

	//create a matlab array that is size of the time of recording
	dims[0] = ChanDur;
	dims[1] = 1;
	plhs[0] = mxCreateNumericArray(2, dims, mxINT32_CLASS, mxREAL);

	ADCdata = mxGetPr(plhs[0]);

	//read in ADCdata
	//mexPrintf("Reading in ADC data.\n");
	readADCdata(hand, numpts, 0, ADCdata, MaxTime);
	
	/*------------------------------------------------------
	Remember to CLOSE THE FILE!
	------------------------------------------------------*/
	flag = SONCloseFile(hand);
}