function snipsout = sorthead_from_raw(shin, channels, snipfile_override)
%SORTHEAD_FROM_RAW: Get snippets extracted by autosort from the .merec
%file.
% shin is 'sorthead' stored in 'overview.mat' generated by autosort.
% channels is a list of channels for which to get snippets
% snipfile_override is the name of the .ssnp to use, in case it has been
%   copied or moved
%%% snipsout is a struct containing fields for snips, snip times, and
%%%   and channel labels.
% last updated by AM 10/22/15 on vivid

%% running from outside the .ssnp file directory may cause errors
%%

if ~exist('channels','var') || isempty(channels)
    snipsout.channels = shin.channels; % if not specified, use all chans
else
    snipsout.channels = channels;
end
    
% use the .ssnp filename listed in the sorthead if an override was not
% specified
if ~exist('snipfile_override','var') || isempty(snipfile_override) 
    snipfile_override = fullfile(shin.fh.abspathstr,shin.fh.filename);
end

snipsout.fh = shin.fh;

nchans = length(snipsout.channels);
snipsout.snips = cell(1,nchans);
snipsout.sniptimes = cell(1,nchans);
for indIndChan = 1:nchans % index within 'channels' input, not within the entire list of channels recorded
    shc = sortheader_importchan_AM(shin,snipsout.channels(indIndChan),snipfile_override);
    snipsout.sniptimes{indIndChan} = shc.sniptimes;  
    nSnipsThisChannel = length(shc.sniptimes);
    snipsout.snips{indIndChan} = cell2mat(sortheader_readsnips(shc,{1:nSnipsThisChannel}));
end

end

