function [fitresult, gof] = createEtlFit(etl, depth)
%CREATEFIT(ETL,DEPTH)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : etl
%      Y Output: depth
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Sep-2016 14:51:35


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( etl, depth );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% % Plot fit with data.
% figure( 'Name', 'Fit to ETL data' );
% h = plot( fitresult, xData, yData );
% legend( h, 'depth vs. etl', 'Fitted Curve', 'Location', 'NorthEast' );
% % Label axes
% xlabel etl
% ylabel depth
% grid on


