% p=1;
% [names{p},paths{p}]=uigetfile('*.mat','pick your files')
% % % Single Envs
close all; clear all;
m=1;
% mouseP(6)=struct('Falls',cell(m),'Rotations',cell(m),'Forwards',cell(m),...
%     'CorrsRun',cell(m),'DistsRun',cell(m),'Corrswoez',cell(m),'Distswoez',cell(m),'Corrs',cell(m),'Dists',cell(m),...
%     'CPP',cell(m),'ybinned',cell(m),'rewards',cell(m),'F0',cell(m),'F08',cell(m),...
%         'mfballout',cell(m),'mtballout',cell(m),'mtaballout',cell(m),'mvrout',cell(m),'mvraout',cell(m),'mPRTAout',cell(m),'reportfigs',cell(m));
    m=1;  
    saveDIR='F:\MA Data\InterneuronsLowerCheck\PVinfo.mat';
    varlist='mouseP';
% curr=12;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(100,1,'E46.100',...
%     {'160208_000_001_hmm1_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\100hz\'},0,'old');
% %save(%saveDIR,varlist);
% 
% %E52
% % load(%saveDIR,varlist);
% m=2;
% curr=3;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(80,1,'E52.2.80',...
%     {'160501_000_000_1_xcorr_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E52.2 80\'},0,'new');
% %save(%saveDIR,varlist);
% 
% curr=4;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(80,1,'E52.3.80',...
%     {'160501_000_001_1_xcorr_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E52.3 80\'},0,'new');
% %save(%saveDIR,varlist);
% 
% 
% curr=5;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(80,1,'E52.4.80',...
%     {'160501_000_002_1_xcorr_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E52.4 80\'},0,'new');
% %save(%saveDIR,varlist);
% 
% curr=6;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(80,1,'E52.5.80',...
%     {'160501_000_003_hmm1_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E52.5 80\'},0,'new');
% %save(%saveDIR,varlist);
% 
% curr=7;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(80,1,'E52.6.80',...
%     {'160502_000_000_1_xcorr_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E52.680\'},0,'new');
% %save(%saveDIR,varlist);
% 
% curr=8;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(80,1,'E52.7.80',...
%     {'160502_000_001_1_xcorr_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E52.780\'},0,'new');
% %save(%saveDIR,varlist);
load(saveDIR,varlist);
m=2;
curr=9;
[mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
    mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
    mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
    mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
    mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
    GeneralInterneuronTestL(80,1,'E52.8.80',...
    {'160503_000_001__XC_1_roibyhand_F.mat'},...
    {'F:\Interneron Videos\E52.8 80\'},0,'new');
save(saveDIR,varlist);
m=2;
curr=10;
[mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
    mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
    mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
    mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
    mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
    GeneralInterneuronTestL(80,1,'E52.9.80byclick',...
    {'160503_000_002_hmm1_roibyclick_nosub_F.mat'},...
    {'F:\Interneron Videos\E52.9 80\'},0,'new');
save(saveDIR,varlist);
m=2;
curr=10;
[mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
    mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
    mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
    mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
    mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
    GeneralInterneuronTestL(80,1,'E52.9.80',...
    {'160503_000_002_hmm1_roibyhand_F.mat'},...
    {'F:\Interneron Videos\E52.9 80\'},0,'new');
save(saveDIR,varlist);
% %M35
% m=3;
% curr=1;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M35.1.120',...
%     {'160518_MA_000_002_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M35\'},0,'new');
% % %save(%saveDIR,varlist);
% % 
% curr=2;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M35.2.120',...
%     {'160519_MA_000_002_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M35\'},0,'new');
% %save(%saveDIR,varlist);
% 
% curr=3;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M35.3.120',...
%     {'160524_MA_000_000_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M35\'},0,'new');
% %save(%saveDIR,varlist);
% 
% curr=4;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M35.4.120',...
%     {'160525_MA_000_001_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M35\'},0,'new');
% %save(%saveDIR,varlist);
% 
% curr=5;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M35.5.120',...
%     {'160527_MA_000_001_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M35\'},0,'new');
% %save(%saveDIR,varlist);
% 
% %M36
% m=4;
% curr=1;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M36.1.120',...
%     {'160525_MA_000_000_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M36\'},0,'new');
% %save(%saveDIR,varlist);
% 
% curr=2;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M36.2.120',...
%     {'160527_MA_000_000_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M36\'},0,'new');
% %save(%saveDIR,varlist);
% 
% 
% %M37
% m=5;
% curr=1;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M37.1.120',...
%     {'160518_MA_000_000_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M37\'},0,'new');
% %save(%saveDIR,varlist);
% 
% curr=2;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M37.2.120',...
%     {'160519_MA_000_000_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M37\'},0,'new');
% %save(%saveDIR,varlist);
% 
% curr=3;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M37.3.120',...
%     {'160524_MA_000_001_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M37\'},0,'new');
% %save(%saveDIR,varlist);
% 
% curr=4;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M37.4.120',...
%     {'160525_MA_000_002_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M37\'},0,'new');
% %save(%saveDIR,varlist);
% 
% curr=5;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M37.5.120',...
%     {'160527_MA_000_002_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M37\'},0,'new');
% %save(%saveDIR,varlist);
% 
% %M41
% % m=6;
% curr=1;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M41.1.120',...
%     {'160518_MA_000_001_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M41\'},0,'new');
% %save(%saveDIR,varlist);
% 
% curr=2;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M41.2.120',...
%     {'160519_MA_000_001_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M41\'},0,'new');
% %save(%saveDIR,varlist);
% 
% curr=3;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(120,1,'M41.3.120',...
%     {'160524_MA_000_002_hmm1_roibyhand_F.mat'},...
%     {'F:\MA Videos\M41\'},0,'new');
% %save(%saveDIR,varlist);


% 
%% PV Rem
% 
% %E46.1
% m=1;
% curr=1;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.1D1',...
%     {'160125_000_002_FFT_1_roibyhand_F.mat','160125_000_002_FFT_2_roibyhand_F.mat',...
%     '160125_000_002_FFT_3_roibyhand_F.mat','160125_000_002_FFT_4_roibyhand_F.mat'},...
%     {'E:\2016\E46.1\160125\','E:\2016\E46.1\160125\',...
%     'E:\2016\E46.1\160125\','E:\2016\E46.1\160125\'},1,'old');
%save(%saveDIR,varlist);

% curr=2;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.1D2',...
%     {'160126_000_000_FFT_1_roibyhand_F.mat','160126_000_000_FFT_2_roibyhand_F.mat',...
%     '160126_000_000_FFT_3_roibyhand_F.mat','160126_000_000_FFT_4_roibyhand_F.mat'},...
%     {'E:\2016\E46.1\160126\','E:\2016\E46.1\160126\',...
%     'E:\2016\E46.1\160126\','E:\2016\E46.1\160126\'},1,'old');
% %save(%saveDIR,varlist);
% 
% curr=3;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.1D3',...
%     {'160127_000_000_FFT_1_roibyhand_F.mat','160127_000_000_FFT_2_roibyhand_F.mat',...
%     '160127_000_000_FFT_3_roibyhand_F.mat','160127_000_000_FFT_4_roibyhand_F.mat'},...
%     {'E:\2016\E46.1\160127\','E:\2016\E46.1\160127\',...
%     'E:\2016\E46.1\160127\','E:\2016\E46.1\160127\'},1,'old');
% %save(%saveDIR,varlist);

% curr=4;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.1D4',...
%     {'160128_000_002_FFT_1_roibyhand_F.mat','160128_000_002_FFT_2_roibyhand_F.mat',...
%     '160128_000_002_FFT_3_roibyhand_F.mat','160128_000_002_FFT_4_roibyhand_F.mat'},...
%     {'E:\2016\E46.1\160128\','E:\2016\E46.1\160128\',...
%     'E:\2016\E46.1\160128\','E:\2016\E46.1\160128\'},1,'old');
% %save(%saveDIR,varlist);

% curr=5;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.1D5',...
%     {'160129_000_001_FFT_1_roibyhand_F.mat','160129_000_001_FFT_2_roibyhand_F.mat',...
%     '160129_000_001_FFT_3_roibyhand_F.mat','160129_000_001_FFT_4_roibyhand_F.mat'},...
%     {'E:\2016\E46.1\160129\','E:\2016\E46.1\160129\',...
%     'E:\2016\E46.1\160129\','E:\2016\E46.1\160129\'},1,'old');
% %save(%saveDIR,varlist);


% % % % E46.2
% 
% curr=6;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.2D1',...
%     {'160201_000_001_hmm1_roibyhand_F.mat','160201_000_001_hmm2_roibyhand_F.mat',...
%     '160201_000_001_hmm3_roibyhand_F.mat','160201_000_001_hmm4_roibyhand_F.mat'},...
%     {'E:\2016\E46.2\160201\','E:\2016\E46.2\160201\',...
%     'E:\2016\E46.2\160201\','E:\2016\E46.2\160201\'},1,'old');
% %save(%saveDIR,varlist);

% 
% curr=7;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.2D2',...
%     {'160202_000_001_hmm1_roibyhand_F.mat','160202_000_001_hmm2_roibyhand_F.mat',...
%     '160202_000_001_hmm3_roibyhand_F.mat','160202_000_001_hmm4_roibyhand_F.mat'},...
%     {'E:\2016\E46.2\160202\','E:\2016\E46.2\160202\',...
%     'E:\2016\E46.2\160202\','E:\2016\E46.2\160202\'},1,'old');
% %save(%saveDIR,varlist);

% curr=8;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.2D3',...
%     {'160203_000_001_hmm1_roibyhand_F.mat','160203_000_001_hmm2_roibyhand_F.mat',...
%     '160203_000_001_hmm3_roibyhand_F.mat','160203_000_001_hmm4_roibyhand_F.mat'},...
%     {'E:\2016\E46.2\160203\','E:\2016\E46.2\160203\',...
%     'E:\2016\E46.2\160203\','E:\2016\E46.2\160203\'},1,'old');
% %save(%saveDIR,varlist);

% 
% curr=9;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.2D4',...
%     {'160204_000_001_hmm1_roibyhand_F.mat','160204_000_001_hmm2_roibyhand_F.mat',...
%     '160204_000_001_hmm3_roibyhand_F.mat','160204_000_001_hmm4_roibyhand_F.mat'},...
%     {'E:\2016\E46.2\160204\','E:\2016\E46.2\160204\',...
%     'E:\2016\E46.2\160204\','E:\2016\E46.2\160204\'},1,'old');
% %save(%saveDIR,varlist);

% 
% curr=10;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.2D5',...
%     {'160205_000_001_hmm1_roibyhand_F.mat','160205_000_001_hmm2_roibyhand_F.mat',...
%     '160205_000_001_hmm3_roibyhand_F.mat','160205_000_001_hmm4_roibyhand_F.mat'},...
%     {'E:\2016\E46.2\160205\','E:\2016\E46.2\160205\',...
%     'E:\2016\E46.2\160205\','E:\2016\E46.2\160205\'},1,'old');
% %save(%saveDIR,varlist);

% 
% curr=11;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.2D6',...
%     {'160207_000_000_hmm1_roibyhand_F.mat','160207_000_000_hmm2_roibyhand_F.mat',...
%     '160207_000_000_hmm3_roibyhand_F.mat','160207_000_000_hmm4_roibyhand_F.mat'},...
%     {'E:\2016\E46.2\160207\','E:\2016\E46.2\160207\',...
%     'E:\2016\E46.2\160207\','E:\2016\E46.2\160207\'},1,'old');
% %save(%saveDIR,varlist);


% % E52.1
% m=2;
% curr=1;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'E52.1D1',...
%     {'160422_000_000_hmm1_roibyhand_F.mat','160422_000_000_hmm2_roibyhand_F.mat',...
%     '160422_000_000_hmm3_roibyhand_F.mat','160422_000_000_hmm4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E52.1\160422\','F:\Interneron Videos\E52.1\160422\',...
%     'F:\Interneron Videos\E52.1\160422\','F:\Interneron Videos\E52.1\160422\'},0,'new',2200);
% %  %save(%saveDIR,varlist);
% 
% curr=2;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'E52.1D2',...
%     {'160424_000_000_hmm1_roibyhand_F.mat','160424_000_000_hmm2_roibyhand_F.mat',...
%     '160424_000_000_hmm3_roibyhand_F.mat','160424_000_000_hmm4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E52.1\160424\','F:\Interneron Videos\E52.1\160424\',...
%     'F:\Interneron Videos\E52.1\160424\','F:\Interneron Videos\E52.1\160424\'},0,'new',2200);
% %  %save(%saveDIR,varlist);
% 
% 
% % M35.1
% 
% m=3;
% curr=6;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'M35.1D1',...
%     {'160601_MA_000_001_hmm1_roibyhand_F.mat','160601_MA_000_001_hmm2_roibyhand_F.mat',...
%     '160601_MA_000_001_hmm3_roibyhand_F.mat','160601_MA_000_001_hmm4_roibyhand_F.mat'},...
%     {'F:\MA Videos\M35\R1\D1\','F:\MA Videos\M35\R1\D1\',...
%     'F:\MA Videos\M35\R1\D1\','F:\MA Videos\M35\R1\D1\'},1,'new',600);
%  %save(%saveDIR,varlist);

% curr=7;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'M35.1D2',...
%     {'160602_MA_000_003_hmm1_roibyhand_F.mat','160602_MA_000_003_hmm2_roibyhand_F.mat',...
%     '160602_MA_000_003_hmm3_roibyhand_F.mat','160602_MA_000_003_hmm4_roibyhand_F.mat'},...
%     {'F:\MA Videos\M35\R1\D2\','F:\MA Videos\M35\R1\D2\',...
%     'F:\MA Videos\M35\R1\D2\','F:\MA Videos\M35\R1\D2\'},1,'new',600);
%  %save(%saveDIR,varlist);

% 
% curr=8;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'M35.1D3',...
%     {'160607_MA_000_002_hmm1_roibyhand_F.mat','160607_MA_000_002_hmm2_roibyhand_F.mat',...
%     '160607_MA_000_002_hmm3_roibyhand_F.mat','160607_MA_000_002_hmm4_roibyhand_F.mat'},...
%     {'F:\MA Videos\M35\R1\D3\','F:\MA Videos\M35\R1\D3\',...
%     'F:\MA Videos\M35\R1\D3\','F:\MA Videos\M35\R1\D3\'},1,'new',600);
%  %save(%saveDIR,varlist);

% curr=9;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'M35.1D4',...
%     {'160608_MA_000_004_hmm1_roibyhand_F.mat','160608_MA_000_004_hmm2_roibyhand_F.mat',...
%     '160608_MA_000_004_hmm3_roibyhand_F.mat','160608_MA_000_004_hmm4_roibyhand_F.mat'},...
%     {'F:\MA Videos\M35\R1\D4\','F:\MA Videos\M35\R1\D4\',...
%     'F:\MA Videos\M35\R1\D4\','F:\MA Videos\M35\R1\D4\'},1,'new',600);
%  %save(%saveDIR,varlist);

% curr=10;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'M35.1D5',...
%     {'160609_MA_000_002_hmm1_roibyhand_F.mat','160609_MA_000_002_hmm2_roibyhand_F.mat',...
%     '160609_MA_000_002_hmm3_roibyhand_F.mat','160609_MA_000_002_hmm4_roibyhand_F.mat'},...
%     {'F:\MA Videos\M35\R1\D5\','F:\MA Videos\M35\R1\D5\',...
%     'F:\MA Videos\M35\R1\D5\','F:\MA Videos\M35\R1\D5\'},1,'new',600);
% %save(%saveDIR,varlist);

 %%
 
% M36.1
% 
% m=4;
% curr=3;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'M36.1D1',...
%     {'160531_MA_000_000_hmm1_roibyhand_F.mat','160531_MA_000_000_hmm2_roibyhand_F.mat',...
%     '160531_MA_000_000_hmm3_roibyhand_F.mat','160531_MA_000_000_hmm4_roibyhand_F.mat'},...
%     {'F:\MA Videos\M36\R1\D1\','F:\MA Videos\M36\R1\D1\',...
%     'F:\MA Videos\M36\R1\D1\','F:\MA Videos\M36\R1\D1\'},1,'new',800);
%  %save(%saveDIR,varlist);

% curr=4;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'M36.1D2',...
%     {'160602_MA_000_002_hmm1_roibyhand_F.mat','160602_MA_000_002_hmm2_roibyhand_F.mat',...
%     '160602_MA_000_002_hmm3_roibyhand_F.mat','160602_MA_000_002_hmm4_roibyhand_F.mat'},...
%     {'F:\MA Videos\M36\R1\D2\','F:\MA Videos\M36\R1\D2\',...
%     'F:\MA Videos\M36\R1\D2\','F:\MA Videos\M36\R1\D2\'},1,'new',800);
%  
% % %save(%saveDIR,varlist);

% curr=5;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'M36.1D3',...
%     {'160603_MA_000_000_hmm1_roibyhand_F.mat','160603_MA_000_000_hmm2_roibyhand_F.mat',...
%     '160603_MA_000_000_hmm3_roibyhand_F.mat','160603_MA_000_000_hmm4_roibyhand_F.mat'},...
%     {'F:\MA Videos\M36\R1\D3\','F:\MA Videos\M36\R1\D3\',...
%     'F:\MA Videos\M36\R1\D3\','F:\MA Videos\M36\R1\D3\'},1,'new',800);
%  %save(%saveDIR,varlist);

% curr=6;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'M36.1D4',...
%     {'160608_MA_000_003_hmm1_roibyhand_F.mat','160608_MA_000_003_hmm2_roibyhand_F.mat',...
%     '160608_MA_000_003_hmm3_roibyhand_F.mat','160608_MA_000_003_hmm4_roibyhand_F.mat'},...
%     {'F:\MA Videos\M36\R1\D4\','F:\MA Videos\M36\R1\D4\',...
%     'F:\MA Videos\M36\R1\D4\','F:\MA Videos\M36\R1\D4\'},1,'new',800);
% %save(%saveDIR,varlist);

% curr=7;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'M36.1D5',...
%     {'160609_MA_000_001_hmm1_roibyhand_F.mat','160609_MA_000_001_hmm2_roibyhand_F.mat',...
%     '160609_MA_000_001_hmm3_roibyhand_F.mat','160609_MA_000_001_hmm4_roibyhand_F.mat'},...
%     {'F:\MA Videos\M36\R1\D5\','F:\MA Videos\M36\R1\D5\',...
%     'F:\MA Videos\M36\R1\D5\','F:\MA Videos\M36\R1\D5\'},1,'new',800);
% %save(%saveDIR,varlist);

% curr=8;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'M36.1D6',...
%     {'160613_MA_000_000_FFT_1_roibyhand_F.mat','160613_MA_000_000_FFT_2_roibyhand_F.mat',...
%     '160613_MA_000_000_FFT_3_roibyhand_F.mat','160613_MA_000_000_FFT_4_roibyhand_F.mat'},...
%     {'F:\MA Videos\M36\R1\D6\','F:\MA Videos\M36\R1\D6\',...
%     'F:\MA Videos\M36\R1\D6\','F:\MA Videos\M36\R1\D6\'},1,'new',800);
%  %save(%saveDIR,varlist);


% M37.1

% m=5;
% curr=6;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(8,2,'M37.1D1',...
%     {'160531_MA_000_002_hmm1_roibyhand_F.mat','160531_MA_000_002_hmm2_roibyhand_F.mat'},...
%     {'F:\MA Videos\M37\R1\D1\','F:\MA Videos\M37\R1\D1\'},1,'new',700);
%  %save(%saveDIR,varlist);

% curr=7;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(8,2,'M37.1D2',...
%     {'160601_MA_000_002_hmm1_roibyhand_F.mat','160601_MA_000_002_hmm2_roibyhand_F.mat'},...
%     {'F:\MA Videos\M37\R1\D2\','F:\MA Videos\M37\R1\D2\'},1,'new',700);
% %save(%saveDIR,varlist);

%M41.1
% 
% m=6;
% curr=4;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr},...
%     mouseP(m).mfballout{curr},mouseP(m).mtballout{curr},mouseP(m).mtaballout{curr},mouseP(m).mvrout{curr},mouseP(m).mvraout{curr},mouseP(m).mPRTAout{curr},mouseP(m).reportfigs{curr}]=...
%     GeneralInterneuronTestL(4,4,'M41.1D1',...
%     {'160607_MA_000_001_hmm1_roibyhand_F.mat','160607_MA_000_001_hmm2_roibyhand_F.mat',...
%     '160607_MA_000_001_hmm3_roibyhand_F.mat','160607_MA_000_001_hmm4_roibyhand_F.mat'},...
%     {'F:\MA Videos\M41\D1\','F:\MA Videos\M41\D1\',...
%     'F:\MA Videos\M41\D1\','F:\MA Videos\M41\D1\'},1,'new',1400);
%save(%saveDIR,varlist);


%E46.5 still needs abfs
% 
% m=1;
% curr=13;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.5D1',...
%     {'160229_000_000_FFT_1_roibyhand_F.mat','160229_000_000_FFT_2_roibyhand_F.mat',...
%     '160229_000_000_FFT_3_roibyhand_F.mat','160229_000_000_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E46.5\D1\','F:\Interneron Videos\E46.5\D1\',...
%     'F:\Interneron Videos\E46.5\D1\','F:\Interneron Videos\E46.5\D1\'},1);
% %save(%saveDIR,varlist);

% curr=14;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.5D2',...
%     {'160301_000_001_FFT_1_roibyhand_F.mat','160301_000_001_FFT_2_roibyhand_F.mat',...
%     '160301_000_001_FFT_3_roibyhand_F.mat','160301_000_001_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E46.5\D2\','F:\Interneron Videos\E46.5\D2\',...
%     'F:\Interneron Videos\E46.5\D2\','F:\Interneron Videos\E46.5\D2\'},1);
% %save(%saveDIR,varlist);

% curr=15;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.5D3',...
%     {'160302_000_000_FFT_1_roibyhand_F.mat','160302_000_000_FFT_2_roibyhand_F.mat',...
%     '160302_000_000_FFT_3_roibyhand_F.mat','160302_000_000_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E46.5\D3\','F:\Interneron Videos\E46.5\D3\',...
%     'F:\Interneron Videos\E46.5\D3\','F:\Interneron Videos\E46.5\D3\'},1);
% %save(%saveDIR,varlist);

% curr=16;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.5D4',...
%     {'160303_000_000_FFT_1_roibyhand_F.mat','160303_000_000_FFT_2_roibyhand_F.mat',...
%     '160303_000_000_FFT_3_roibyhand_F.mat','160303_000_000_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E46.5\D4\','F:\Interneron Videos\E46.5\D4\',...
%     'F:\Interneron Videos\E46.5\D4\','F:\Interneron Videos\E46.5\D4\'},1);
% %save(%saveDIR,varlist);

% curr=17;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.5D5',...
%     {'160304_000_001_FFT_1_roibyhand_F.mat','160304_000_001_FFT_2_roibyhand_F.mat',...
%     '160304_000_001_FFT_3_roibyhand_F.mat','160304_000_001_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E46.5\D5\','F:\Interneron Videos\E46.5\D5\',...
%     'F:\Interneron Videos\E46.5\D5\','F:\Interneron Videos\E46.5\D5\'},1);
% %save(%saveDIR,varlist);

% curr=18;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.5D6',...
%     {'160307_000_001_FFT_1_roibyhand_F.mat','160307_000_001_FFT_2_roibyhand_F.mat',...
%     '160307_000_001_FFT_3_roibyhand_F.mat','160307_000_001_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E46.5\D6\','F:\Interneron Videos\E46.5\D6\',...
%     'F:\Interneron Videos\E46.5\D6\','F:\Interneron Videos\E46.5\D6\'},1);
% %save(%saveDIR,varlist);

% curr=19;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.5D7',...
%     {'160308_000_001_FFT_1_roibyhand_F.mat','160308_000_001_FFT_2_roibyhand_F.mat',...
%     '160308_000_001_FFT_3_roibyhand_F.mat','160308_000_001_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E46.5\D7\','F:\Interneron Videos\E46.5\D7\',...
%     'F:\Interneron Videos\E46.5\D7\','F:\Interneron Videos\E46.5\D7\'},1);
% %save(%saveDIR,varlist);

% curr=20;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.5D8',...
%     {'160309_000_001_FFT_1_roibyhand_F.mat','160309_000_001_FFT_2_roibyhand_F.mat',...
%     '160309_000_001_FFT_3_roibyhand_F.mat','160309_000_001_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E46.5\D8\','F:\Interneron Videos\E46.5\D8\',...
%     'F:\Interneron Videos\E46.5\D8\','F:\Interneron Videos\E46.5\D8\'},1);
% %save(%saveDIR,varlist);

% curr=21;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.5D9',...
%     {'160310_000_001_FFT_1_roibyhand_F.mat','160310_000_001_FFT_2_roibyhand_F.mat',...
%     '160310_000_001_FFT_3_roibyhand_F.mat','160310_000_001_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E46.5\D9\','F:\Interneron Videos\E46.5\D9\',...
%     'F:\Interneron Videos\E46.5\D9\','F:\Interneron Videos\E46.5\D9\'},1);
% %save(%saveDIR,varlist);

% curr=22;
% [mouseP(m).Falls{curr},mouseP(m).Rotations{curr},mouseP(m).Forwards{curr},...
%     mouseP(m).Corrs{curr},mouseP(m).Dists{curr},mouseP(m).CPP{curr},mouseP(m).ybinned{curr},...
%     mouseP(m).rewards{curr},mouseP(m).F0{curr},mouseP(m).F08{curr},mouseP(m).DistsRun{curr},...
%     mouseP(m).CorrsRun{curr},mouseP(m).Distswoez{curr},mouseP(m).Corrswoez{curr}]=...
%     GeneralInterneuronTestL(4,4,'E46.5D10',...
%     {'160315_000_000_FFT_1_roibyhand_F.mat','160315_000_000_FFT_2_roibyhand_F.mat',...
%     '160315_000_000_FFT_3_roibyhand_F.mat','160315_000_000_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E46.5\D10\','F:\Interneron Videos\E46.5\D10\',...
%     'F:\Interneron Videos\E46.5\D10\','F:\Interneron Videos\E46.5\D10\'},1);
% %save(%saveDIR,varlist);

%save('F:\MA Data\Interneurons\PVinfo.mat','mouseP');
% plot_PV_figs

% %%
% 
% 
% 
% 
% 
% 
% % 
% 
% % %%
% for p=1:4
%     [names{p},paths{p}]=uigetfile('*.mat','pick your files');
%     names{p}
%     paths{p}
% end
