% % [names{p},paths{p}]=uigetfile('*.mat','pick your files')
% % Single Envs
% % mouse(6)=struct('Falls',cell(m),'Rotations',cell(m),'Forwards',cell(m),...
% %     'CorrsRun',cell(m),'DistsRun',cell(m),'Corrswoez',cell(m),'Distswoez',cell(m),'Corrs',cell(m),'Dists',cell(m),...
% %     'CPP',cell(m),'ybinned',cell(m),'rewards',cell(m),'F0',cell(m),'F08',cell(m),...
% %         'mfballout',cell(m),'mtballout',cell(m),'mtaballout',cell(m),'mvrout',cell(m),'mvraout',cell(m),'mPRTAout',cell(m),'reportfigs',cell(m),'dFcorr',cell(m));
% mouse=struct();
m=3;
saveDir='F:\MA Data\Interneurons\SSTinfo.mat';
    varlist='mouse';
% curr=1;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(120,1,'E49.120',...
%     {'160512_000_001_1_xcorr_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E49\E49.120\'},0,'new');
% save(saveDir,varlist);
% % % 
% m=3;
% curr=7;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(80,1,'E49.6.80',...
%     {'160429_000_003_hmm1_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E49\E49.6.80\'},0,'new');
% %save(%saveDir,varlist);
% % % 
% curr=8;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(120,1,'E49.7.80',...
%     {'160429_000_004__XC_1_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E49\E49.7.80\'},0,'new');
% % % save(%saveDir,varlist);
% % % 
% m=4;
% curr=1;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(120,1,'E50.120',...
%     {'160512_000_000_1_xcorr_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E50\E50.120\'},0,'new');
% % % save(%saveDir,varlist);
% % 
% m=3;
% curr=2;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(80,1,'E49.1.80',...
%     {'160427_000_002_hmm1_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E49\E49.1.80\'},0,'new');
% % % save(saveDir,varlist);
% % % 
% m=3;
% curr=3;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(80,1,'E49.2.80',...
%     {'160428_000_002_hmm1_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E49\E49.2.80\'},0,'new');
% % %save(%saveDir,varlist);
% 
% % % % m=3;
% % % % curr=9;
% % % % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% % % %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% % % %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% % % %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
% % % %     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
% % % %     GeneralInterneuronTest(80,1,'E49.8.80D1',...
% % % %     {'160503_000_005_1_xcorr_roibyhand_F.mat'},...
% % % %     {'F:\Final F_Files for INs\SST\E49\E49.8.80\D1\'},0,'new');
% % % % % save(saveDir,varlist);
% % % % m=3;
% % % % curr=10;
% % % % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% % % %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% % % %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% % % %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
% % % %     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
% % % %     GeneralInterneuronTest(80,1,'E49.8.80D2',...
% % % %     {'160503_000_006_1_xcorr_roibyhand_F.mat'},...
% % % %     {'F:\Final F_Files for INs\SST\E49\E49.8.80\D2\'},0,'new');
% % % % save(saveDir,varlist);
load(saveDir,varlist);
m=3;
curr=19;
[mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
    mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
    mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
    mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
    mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
    GeneralInterneuronTest(26,1,'E49.5.26',...
    {'160414_000_001_hmm1_roibyhand_F.mat'},...
    {'F:\Final F_Files for INs\SST\E49\E49.5.26\'},0,'new');
save(saveDir,varlist);
% 
% m=3;
% curr=18;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E49.13',...
%     {'160419_000_001__XC_1_roibyhand_F.mat','160419_000_001__XC_2_roibyhand_F.mat',...
%     '160419_000_001__XC_3_roibyhand_F.mat','160419_000_001__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E49\E49.13\','F:\Final F_Files for INs\SST\E49\E49.13\',...
%     'F:\Final F_Files for INs\SST\E49\E49.13\','F:\Final F_Files for INs\SST\E49\E49.13\'},0,'old');
% save(saveDir,varlist);
% 
% m=4;
% curr=4;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(80,1,'E50.3.80',...
%     {'160503_000_004_hmm1_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E50\E50.3.80\'},0,'old');
% save(saveDir,varlist);
% 
% % % % % m=1;
% % % % % curr=11;
% % % % % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% % % % %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% % % % %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% % % % %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
% % % % %     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
% % % % %     GeneralInterneuronTest(4,4,'E49.11.94',...
% % % % %     {'160419_000_001_hmm1_roibyhand_F.mat','160419_000_002_hmm1_roibyhand_F.mat',...
% % % % %     '160419_000_001_hmm3_roibyhand_F.mat','160419_000_004_hmm1_roibyhand_F.mat'},...
% % % % %     {'F:\Interneron Videos\E49.13','F:\Interneron Videos\E49.13',...
% % % % %     'F:\Interneron Videos\E49.13','F:\Interneron Videos\E49.13'},1,'old');
% % % % % %save(%saveDir,varlist);
% % % % % 
% % % % % m=1;
% % % % % curr=12;
% % % % % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% % % % %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% % % % %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% % % % %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
% % % % %     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
% % % % %     GeneralInterneuronTest(4,4,'E49.11.94',...
% % % % %     {'160419_000_001_hmm1_roibyhand_F.mat','160419_000_002_hmm1_roibyhand_F.mat',...
% % % % %     '160419_000_001_hmm3_roibyhand_F.mat','160419_000_004_hmm1_roibyhand_F.mat'},...
% % % % %     {'F:\Interneron Videos\E49.13','F:\Interneron Videos\E49.13',...
% % % % %     'F:\Interneron Videos\E49.13','F:\Interneron Videos\E49.13'},1,'old');
% % % % % % save(%saveDir,varlist);
% 
% 
% % % %
% load(saveDir,varlist);
% 
% m=2;
% curr=26;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.5D1',...
%     {'1214_000_000__XC_1_roibyhand_F.mat','1214_000_000__XC_2_roibyhand_F.mat',...
%     '1214_000_000__XC_2_roibyhand_F.mat','1214_000_000__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E32\E32.5\D1\','F:\Final F_Files for INs\SST\E32\E32.5\D1\',...
%     'F:\Final F_Files for INs\SST\E32\E32.5\D1\','F:\Final F_Files for INs\SST\E32\E32.5\D1\'},1,'old');
% %save(%saveDir,varlist);
% % 
% m=2;
% curr=27;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.5D2',...
%     {'1218_000_000__XC_1_roibyhand_F.mat','1218_000_000__XC_2_roibyhand_F.mat',...
%     '1218_000_000__XC_2_roibyhand_F.mat','1218_000_000__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E32\E32.5\D2\','F:\Final F_Files for INs\SST\E32\E32.5\D2\',...
%     'F:\Final F_Files for INs\SST\E32\E32.5\D2\','F:\Final F_Files for INs\SST\E32\E32.5\D2\'},1,'old');
% save(saveDir,varlist);
% 
% % 
% m=3;
% curr=4;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E49.2D1',...
%     {'160417_000_001__XC_1_roibyhand_F.mat','160417_000_001__XC_2_roibyhand_F.mat',...
%     '160417_000_001__XC_3_roibyhand_F.mat','160417_000_001__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E49\E49.2\D1\','F:\Final F_Files for INs\SST\E49\E49.2\D1\',...
%     'F:\Final F_Files for INs\SST\E49\E49.2\D1\','F:\Final F_Files for INs\SST\E49\E49.2\D1\'},0,'new',4095);
% %save(%saveDir,varlist);
% % 
% m=3;
% curr=5;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E49.2D2',...
%     {'160418_000_002__XC_1_roibyhand_F.mat','160418_000_002__XC_2_roibyhand_F.mat',...
%     '160418_000_002__XC_3_roibyhand_F.mat','160418_000_002__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E49\E49.2\D2\','F:\Final F_Files for INs\SST\E49\E49.2\D2\',...
%     'F:\Final F_Files for INs\SST\E49\E49.2\D2\','F:\Final F_Files for INs\SST\E49\E49.2\D2\',0,'new',2200});
% %save(%saveDir,varlist);
% 
% m=4;
% curr=2;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E50.1D1',...
%     {'160417_000_000__XC_1_roibyhand_F.mat','160417_000_000__XC_2_roibyhand_F.mat',...
%     '160417_000_000__XC_3_roibyhand_F.mat','160417_000_000__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E50\E50.1\D1\','F:\Final F_Files for INs\SST\E50\E50.1\D1\',...
%     'F:\Final F_Files for INs\SST\E50\E50.1\D1\','F:\Final F_Files for INs\SST\E50\E50.1\D1\'},0,'new',4095);
% %save(%saveDir,varlist);
% % 
% m=4;
% curr=3;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E50.1D2',...
%     {'160420_000_000__XC_1_roibyhand_F.mat','160420_000_000__XC_2_roibyhand_F.mat',...
%     '160420_000_000__XC_3_roibyhand_F.mat','160420_000_000__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E50\E50.1\D2\','F:\Final F_Files for INs\SST\E50\E50.1\D2\',...
%     'F:\Final F_Files for INs\SST\E50\E50.1\D2\','F:\Final F_Files for INs\SST\E50\E50.1\D2\'},0,'new',1400);
% save(saveDir,varlist);
% 
% 
% 
% % % % % 
% % % 
% % % % 
% % % % 
% % % % 
% % % % 
% % % 
% %% Two Envs
% % % 
% % %% SST NO VR
% % 
% % % E32.6
% m=2;
% curr=28;
% 
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.6D1',...
%     {'1215_000_000-002__XC_1_roibyhand_F','1215_000_000-002__XC_2_roibyhand_F',...
%     '1215_000_000-002__XC_2_roibyhand_F','1215_000_000-002__XC_4_roibyhand_F'},...
%     {'F:\Final F_Files for INs\SST\E32\E32.6\D1\','F:\Final F_Files for INs\SST\E32\E32.6\D1\',...
%     'F:\Final F_Files for INs\SST\E32\E32.6\D1\','F:\Final F_Files for INs\SST\E32\E32.6\D1\'},1,'old');
% save(saveDir,varlist);
% 
% m=2;
% curr=29;
% 
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.6D2',...
%     {'1216_000_000-002__XC_1_roibyhand_F.mat','1216_000_000-002__XC_2_roibyhand_F.mat',...
%     '1216_000_000-002__XC_3_roibyhand_F.mat','1216_000_000-002__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E32\E32.6\D2\','F:\Final F_Files for INs\SST\E32\E32.6\D2\',...
%     'F:\Final F_Files for INs\SST\E32\E32.6\D2\','F:\Final F_Files for INs\SST\E32\E32.6\D2\'},1,'old');
% save(saveDir,varlist);
% 
% m=2;
% curr=30;
% 
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.6D3',...
%     {'1217_000_000-002__XC_1_roibyhand_F.mat','1217_000_000-002__XC_2_roibyhand_F.mat',...
%     '1217_000_000-002__XC_3_roibyhand_F.mat','1217_000_000-002__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E32\E32.6\D3\','F:\Final F_Files for INs\SST\E32\E32.6\D3\',...
%     'F:\Final F_Files for INs\SST\E32\E32.6\D3\','F:\Final F_Files for INs\SST\E32\E32.6\D3\'},1,'old');
% save(saveDir,varlist);
load(saveDir,varlist);

m=6;
curr=1;

[mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
    mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
    mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
    mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
    mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
    GeneralInterneuronTest(4,4,'X14.1D1',...
    {'1228_000_002__XC_1_roibyhand_F.mat','1228_000_002__XC_2_roibyhand_F.mat',...
    '1228_000_002__XC_3_roibyhand_F.mat','1228_000_002__XC_4_roibyhand_F.mat'},...
    {'F:\Final F_Files for INs\SST\X14\X14nVr\D1\','F:\Final F_Files for INs\SST\X14\X14nVr\D1\',...
    'F:\Final F_Files for INs\SST\X14\X14nVr\D1\','F:\Final F_Files for INs\SST\X14\X14nVr\D1\'},1,'old');
save(saveDir,varlist);

m=6;
curr=1;

[mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
    mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
    mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
    mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
    mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
    GeneralInterneuronTest(4,4,'X14.1D2',...
    {'1229_000_002__XC_1_roibyhand_F.mat','1229_000_002__XC_2_roibyhand_F.mat',...
    '1229_000_002__XC_3_roibyhand_F.mat','1229_000_002__XC_4_roibyhand_F.mat'},...
    {'F:\Final F_Files for INs\SST\X14\X14nVr\D2\','F:\Final F_Files for INs\SST\X14\X14nVr\D2\',...
    'F:\Final F_Files for INs\SST\X14\X14nVr\D2\','F:\Final F_Files for INs\SST\X14\X14nVr\D2\'},1,'old');
save(saveDir,varlist);

% %% SST Rem
% % 
% % % E31.1
% load(saveDir,varlist);
% m=1;
% curr=1;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E31.1D1',...
%     {'1119_000_000__XC_1_roibyhand_F.mat','1119_000_000__XC_2_roibyhand_F.mat',...
%     '1119_000_000__XC_3_roibyhand_F.mat','1119_000_000__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E31\E31.1\D1\','F:\Final F_Files for INs\SST\E31\E31.1\D1\',...
%     'F:\Final F_Files for INs\SST\E31\E31.1\D1\','F:\Final F_Files for INs\SST\E31\E31.1\D1\'},1,'old');
% 
% save(saveDir,varlist);
% 
%  
% m=1;
% curr=2;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E31.1D2',...
%     {'1120_000_001__XC_1_roibyhand_F.mat','1120_000_001__XC_2_roibyhand_F.mat',...
%     '1120_000_001__XC_3_roibyhand_F.mat','1120_000_001__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E31\E31.1\D2\','F:\Final F_Files for INs\SST\E31\E31.1\D2\',...
%     'F:\Final F_Files for INs\SST\E31\E31.1\D2\','F:\Final F_Files for INs\SST\E31\E31.1\D2\'},1,'old');
% % %save(%saveDir,varlist);
% 
% m=1;
% curr=3;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E31.1D3',...
%     {'1122_000_000__XC_1_roibyhand_F.mat','1122_000_000__XC_2_roibyhand_F.mat',...
%     '1122_000_000__XC_3_roibyhand_F.mat','1122_000_000__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E31\E31.1\D3\','F:\Final F_Files for INs\SST\E31\E31.1\D3\',...
%     'F:\Final F_Files for INs\SST\E31\E31.1\D3\','F:\Final F_Files for INs\SST\E31\E31.1\D3\'},1,'old');
% % %save(%saveDir,varlist);
% 
% m=1;
% curr=4;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E31.1D4',...
%     {'1123_000_000__XC_1_roibyhand_F.mat','1123_000_000__XC_2_roibyhand_F.mat',...
%     '1123_000_000__XC_3_roibyhand_F.mat','1123_000_000__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E31\E31.1\D4\','F:\Final F_Files for INs\SST\E31\E31.1\D4\',...
%     'F:\Final F_Files for INs\SST\E31\E31.1\D4\','F:\Final F_Files for INs\SST\E31\E31.1\D4\'},1,'old');
% % %save(%saveDir,varlist);
% 
% m=1;
% curr=5;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E31.1D5',...
%     {'1124_000_000__XC_1_roibyhand_F.mat','1124_000_000__XC_2_roibyhand_F.mat',...
%     '1124_000_000__XC_3_roibyhand_F.mat','1124_000_000__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E31\E31.1\D5\','F:\Final F_Files for INs\SST\E31\E31.1\D5\',...
%     'F:\Final F_Files for INs\SST\E31\E31.1\D5\','F:\Final F_Files for INs\SST\E31\E31.1\D5\'},1,'old');
% %save(%saveDir,varlist);
% 
% %E49.12 (saline remapping)
% m=3;
% curr=13;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E49.12D1',...
%     {'160516_000_002__XC_1_roibyhand_F.mat','160516_000_002__XC_2_roibyhand_F.mat',...
%     '160516_000_002__XC_3_roibyhand_F.mat','160516_000_002__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E49\E49.12 SR\D1\','F:\Final F_Files for INs\SST\E49\E49.12 SR\D1\',...
%     'F:\Final F_Files for INs\SST\E49\E49.12 SR\D1\','F:\Final F_Files for INs\SST\E49\E49.12 SR\D1\'},1,'old');
% save(saveDir,varlist);
% 
% m=3;
% curr=14;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E49.12D2',...
%     {'160517_000_003__XC_1_roibyhand_F.mat','160517_000_003__XC_2_roibyhand_F.mat',...
%     '160517_000_003__XC_3_roibyhand_F.mat','160517_000_003__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E49\E49.12 SR\D2\','F:\Final F_Files for INs\SST\E49\E49.12 SR\D2\',...
%     'F:\Final F_Files for INs\SST\E49\E49.12 SR\D2\','F:\Final F_Files for INs\SST\E49\E49.12 SR\D2\'},1,'old');
% % %save(saveDir,varlist);
% m=3;
% curr=15;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E49.12D3',...
%     {'160518_000_001__XC_1_roibyhand_F.mat','160518_000_001__XC_2_roibyhand_F.mat',...
%     '160518_000_001__XC_3_roibyhand_F.mat','160518_000_001__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E49\E49.12 SR\D3\','F:\Final F_Files for INs\SST\E49\E49.12 SR\D3\',...
%     'F:\Final F_Files for INs\SST\E49\E49.12 SR\D3\','F:\Final F_Files for INs\SST\E49\E49.12 SR\D3\'},1,'old');
% % %save(saveDir,varlist);
% m=3;
% curr=16;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E49.12D4',...
%     {'160519_000_001__XC_1_roibyhand_F.mat','160519_000_001__XC_2_roibyhand_F.mat',...
%     '160519_000_001__XC_3_roibyhand_F.mat','160519_000_001__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E49\E49.12 SR\D4\','F:\Final F_Files for INs\SST\E49\E49.12 SR\D4\',...
%     'F:\Final F_Files for INs\SST\E49\E49.12 SR\D4\','F:\Final F_Files for INs\SST\E49\E49.12 SR\D4\'},1,'old');
% % %save(saveDir,varlist);
% m=3;
% curr=17;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E49.12D5',...
%     {'160520_000_000__XC_1_roibyhand_F.mat','160520_000_000__XC_2_roibyhand_F.mat',...
%     '160520_000_000__XC_3_roibyhand_F.mat','160520_000_000__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E49\E49.12 SR\D5\','F:\Final F_Files for INs\SST\E49\E49.12 SR\D5\',...
%     'F:\Final F_Files for INs\SST\E49\E49.12 SR\D5\','F:\Final F_Files for INs\SST\E49\E49.12 SR\D5\'},1,'old');
% save(saveDir,varlist);
% 
% %E50.5 (saline remapping)
% m=4;
% curr=10;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E50.5D1',...
%     {'160516_000_001__XC_1_roibyhand_F.mat','160516_000_001__XC_2_roibyhand_F.mat',...
%     '160516_000_001__XC_3_roibyhand_F.mat','160516_000_001__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E50\E50.5 SR\D1\','F:\Final F_Files for INs\SST\E50\E50.5 SR\D1\',...
%     'F:\Final F_Files for INs\SST\E50\E50.5 SR\D1\','F:\Final F_Files for INs\SST\E50\E50.5 SR\D1\'},1,'old');
% % %save(saveDir,varlist);
% 
% m=4;
% curr=11;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E50.5D2',...
%     {'160517_000_001__XC_1_roibyhand_F.mat','160517_000_001__XC_2_roibyhand_F.mat',...
%     '160517_000_001__XC_3_roibyhand_F.mat','160517_000_001__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E50\E50.5 SR\D2\','F:\Final F_Files for INs\SST\E50\E50.5 SR\D2\',...
%     'F:\Final F_Files for INs\SST\E50\E50.5 SR\D2\','F:\Final F_Files for INs\SST\E50\E50.5 SR\D2\'},1,'old');
% % %save(saveDir,varlist);
m=4;
curr=12;
[mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
    mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
    mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
    mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
    mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
    GeneralInterneuronTest(4,4,'E50.5D3',...
    {'160518_000_000__XC_1_roibyhand_F.mat','160518_000_000__XC_2_roibyhand_F.mat',...
    '160518_000_000__XC_3_roibyhand_F.mat','160518_000_000__XC_4_roibyhand_F.mat'},...
    {'F:\Final F_Files for INs\SST\E50\E50.5 SR\D3\','F:\Final F_Files for INs\SST\E50\E50.5 SR\D3\',...
    'F:\Final F_Files for INs\SST\E50\E50.5 SR\D3\','F:\Final F_Files for INs\SST\E50\E50.5 SR\D3\'},1,'old');
save(saveDir,varlist);
% m=4;
% curr=13;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E50.5D4',...
%     {'160519_000_000__XC_1_roibyhand_F.mat','160519_000_000__XC_2_roibyhand_F.mat',...
%     '160519_000_000__XC_3_roibyhand_F.mat','160519_000_000__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E50\E50.5 SR\D4\','F:\Final F_Files for INs\SST\E50\E50.5 SR\D4\',...
%     'F:\Final F_Files for INs\SST\E50\E50.5 SR\D4\','F:\Final F_Files for INs\SST\E50\E50.5 SR\D4\'},1,'old');
% % %save(saveDir,varlist);
% m=4;
% curr=14;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E50.5D5',...
%     {'160520_000_001__XC_1_roibyhand_F.mat','160520_000_001__XC_2_roibyhand_F.mat',...
%     '160520_000_001__XC_3_roibyhand_F.mat','160520_000_001__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\E50\E50.5 SR\D5\','F:\Final F_Files for INs\SST\E50\E50.5 SR\D5\',...
%     'F:\Final F_Files for INs\SST\E50\E50.5 SR\D5\','F:\Final F_Files for INs\SST\E50\E50.5 SR\D5\'},1,'old');
% save(saveDir,varlist);
% 
% % 
% % 
% % 
% % % X13.1
% % % 
% m=5;
% curr=1;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'X13.1D1',...
%     {'160118_000_003__XC_1_roibyhand_F.mat','160118_000_003__XC_2_roibyhand_F.mat',...
%     '160118_000_003__XC_3_roibyhand_F.mat','160118_000_003__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\X13\X13.1\D1\','F:\Final F_Files for INs\SST\X13\X13.1\D1\',...
%     'F:\Final F_Files for INs\SST\X13\X13.1\D1\','F:\Final F_Files for INs\SST\X13\X13.1\D1\'},1,'old');
% %save(%saveDir,varlist);
% % 
% 
% 
% 
% m=5;
% curr=2;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'X13.1D2',...
%     {'160119_000_003__XC_1_roibyhand_F.mat','160119_000_003__XC_2_roibyhand_F.mat',...
%     '160119_000_003__XC_3_roibyhand_F.mat','160119_000_003__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\X13\X13.1\D2\','F:\Final F_Files for INs\SST\X13\X13.1\D2\',...
%     'F:\Final F_Files for INs\SST\X13\X13.1\D2\','F:\Final F_Files for INs\SST\X13\X13.1\D2\'},1,'old');
% %save(%saveDir,varlist);
% 
% 
% 
% m=5;
% curr=3;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'X13.1D3',...
%     {'160120_000_003__XC_1_roibyhand_F.mat','160120_000_003__XC_2_roibyhand_F.mat',...
%     '160120_000_003__XC_3_roibyhand_F.mat','160120_000_003__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\X13\X13.1\D3\','F:\Final F_Files for INs\SST\X13\X13.1\D3\',...
%     'F:\Final F_Files for INs\SST\X13\X13.1\D3\','F:\Final F_Files for INs\SST\X13\X13.1\D3\'},1,'old');
% %save(%saveDir,varlist);
% 
% 
% 
% m=5;
% curr=4;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'X13.1D4',...
%     {'160121_000_002__XC_1_roibyhand_F.mat','160121_000_002__XC_2_roibyhand_F.mat',...
%     '160121_000_002__XC_3_roibyhand_F.mat','160121_000_002__XC_4_roibyhand_F.mat'},...
%     {'F:\Final F_Files for INs\SST\X13\X13.1\D4\','F:\Final F_Files for INs\SST\X13\X13.1\D4\',...
%     'F:\Final F_Files for INs\SST\X13\X13.1\D4\','F:\Final F_Files for INs\SST\X13\X13.1\D4\'},1,'old');
% %save(%saveDir,varlist);
% 
% % 
% % 
% % 
% % E32.4
% 
% m=2;
% curr=14;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.4D1',...
%     {'160106_000_000_FFT_1_roibyhand_F.mat','160106_000_000_FFT_2_roibyhand_F.mat',...
%     '160106_000_000_FFT_3_roibyhand_F.mat','160106_000_000_FFT_4_roibyhand_F.mat'},...
%     {'E:\2016\E32.4\160106\','E:\2016\E32.4\160106\',...
%     'E:\2016\E32.4\160106\','E:\2016\E32.4\160106\'},1,'old');
% % save(%saveDir,varlist);
% 
% 
% 
% m=2;
% curr=15;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.4D2',...
%     {'160107_000_000_FFT_1_roibyhand_F.mat','160107_000_000_FFT_2_roibyhand_F.mat',...
%     '160107_000_000_FFT_3_roibyhand_F.mat','160107_000_000_FFT_4_roibyhand_F.mat'},...
%     {'E:\2016\E32.4\160107\','E:\2016\E32.4\160107\',...
%     'E:\2016\E32.4\160107\','E:\2016\E32.4\160107\'},1,'old');
% %save(%saveDir,varlist);
% 
% 
% 
% m=2;
% curr=16;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.4D3',...
%     {'160108_000_000_FFT_1_roibyhand_F.mat','160108_000_000_FFT_2_roibyhand_F.mat',...
%     '160108_000_000_FFT_3_roibyhand_F.mat','160108_000_000_FFT_4_roibyhand_F.mat'},...
%     {'E:\2016\E32.4\160108\','E:\2016\E32.4\160108\',...
%     'E:\2016\E32.4\160108\','E:\2016\E32.4\160108\'},1,'old');
% %save(%saveDir,varlist);
% 
% 
% 
% m=2;
% curr=17;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...]=...
%     GeneralInterneuronTest(4,4,'E32.4D4',...
%     {'160112_000_000_FFT_1_roibyhand_F.mat','160112_000_000_FFT_2_roibyhand_F.mat',...
%     '160112_000_000_FFT_3_roibyhand_F.mat','160112_000_000_FFT_4_roibyhand_F.mat'},...
%     {'E:\2016\E32.4\160112\','E:\2016\E32.4\160112\',...
%     'E:\2016\E32.4\160112\','E:\2016\E32.4\160112\'},1,'old');
% %save(%saveDir,varlist);
% 
% 
% 
% m=2;
% curr=18;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.4D5',...
%     {'160113_000_003_FFT_1_roibyhand_F.mat','160113_000_003_FFT_2_roibyhand_F.mat',...
%     '160113_000_003_FFT_3_roibyhand_F.mat','160113_000_003_FFT_4_roibyhand_F.mat'},...
%     {'E:\2016\E32.4\160113\','E:\2016\E32.4\160113\',...
%     'E:\2016\E32.4\160113\','E:\2016\E32.4\160113\'},1,'old');
% %save(%saveDir,varlist);
% 
% 
% m=2;
% curr=19;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.4D6',...
%     {'160114_000_003_FFT_1_roibyhand_F.mat','160114_000_003_FFT_2_roibyhand_F.mat',...
%     '160114_000_003_FFT_3_roibyhand_F.mat','160114_000_003_FFT_4_roibyhand_F.mat'},...
%     {'E:\2016\E32.4\160114\','E:\2016\E32.4\160114\',...
%     'E:\2016\E32.4\160114\','E:\2016\E32.4\160114\'},1,'old');
% %save(%saveDir,varlist);
% 
% 
% 
% m=2;
% curr=20;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.4D7',...
%     {'160115_000_003_FFT_1_roibyhand_F.mat','160115_000_003_FFT_2_roibyhand_F.mat',...
%     '160115_000_003_FFT_3_roibyhand_F.mat','160115_000_003_FFT_4_roibyhand_F.mat'},...
%     {'E:\2016\E32.4\160115\','E:\2016\E32.4\160115\',...
%     'E:\2016\E32.4\160115\','E:\2016\E32.4\160115\'},1,'old');
% %save(%saveDir,varlist);
% 
% 
% m=2;
% curr=21;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.4D8',...
%     {'160118_000_005_FFT_1_roibyhand_F.mat','160118_000_005_FFT_2_roibyhand_F.mat',...
%     '160118_000_005_FFT_3_roibyhand_F.mat','160118_000_005_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E32.4 18-22\160118\','F:\Interneron Videos\E32.4 18-22\160118\',...
%     'F:\Interneron Videos\E32.4 18-22\160118\','F:\Interneron Videos\E32.4 18-22\160118\'},1,'old');
% %save(%saveDir,varlist);
% 
% 
% 
% m=2;
% curr=22;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.4D9',...
%     {'160119_000_005_FFT_1_roibyhand_F.mat','160119_000_005_FFT_2_roibyhand_F.mat',...
%     '160119_000_005_FFT_3_roibyhand_F.mat','160119_000_005_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E32.4 18-22\160119\','F:\Interneron Videos\E32.4 18-22\160119\',...
%     'F:\Interneron Videos\E32.4 18-22\160119\','F:\Interneron Videos\E32.4 18-22\160119\'},1,'old');
% %save(%saveDir,varlist);
% 
% 
% m=2;
% curr=23;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.4D10',...
%     {'160120_000_005_FFT_1_roibyhand_F.mat','160120_000_005_FFT_2_roibyhand_F.mat',...
%     '160120_000_005_FFT_3_roibyhand_F.mat','160120_000_005_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E32.4 18-22\160120\','F:\Interneron Videos\E32.4 18-22\160120\',...
%     'F:\Interneron Videos\E32.4 18-22\160120\','F:\Interneron Videos\E32.4 18-22\160120\'},1,'old');
% %save(%saveDir,varlist);
% 
% 
% m=2;
% curr=24;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.4D11',...
%     {'160121_000_004_FFT_1_roibyhand_F.mat','160121_000_004_FFT_2_roibyhand_F.mat',...
%     '160121_000_004_FFT_3_roibyhand_F.mat','160121_000_004_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E32.4 18-22\160121\','F:\Interneron Videos\E32.4 18-22\160121\',...
%     'F:\Interneron Videos\E32.4 18-22\160121\','F:\Interneron Videos\E32.4 18-22\160121\'},1,'old');
% %save(%saveDir,varlist);
% 
% 
% m=2;
% curr=25;
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
%     mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
%     GeneralInterneuronTest(4,4,'E32.4D12',...
%     {'160122_000_017_FFT_1_roibyhand_F.mat','160122_000_017_FFT_2_roibyhand_F.mat',...
%     '160122_000_017_FFT_3_roibyhand_F.mat','160122_000_017_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\E32.4 18-22\160122\','F:\Interneron Videos\E32.4 18-22\160122\',...
%     'F:\Interneron Videos\E32.4 18-22\160122\','F:\Interneron Videos\E32.4 18-22\160122\'},1,'old');
% save(saveDir,varlist);
% % 
% 
% 
% % 
% % 
% E50.2
load(saveDir,varlist);
m=4;
curr=5;
[mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
    mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
    mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
    mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
    mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
    GeneralInterneuronTest(4,4,'E50.2D1',...
    {'160419_000_000__XC_1_roibyhand_F.mat','160419_000_000__XC_2_roibyhand_F.mat',...
    '160419_000_000__XC_3_roibyhand_F.mat','160419_000_000__XC_4_roibyhand_F.mat'},...
    {'F:\Final F_Files for INs\SST\E50\E50.2\D2\','F:\Final F_Files for INs\SST\E50\E50.2\D2\',...
    'F:\Final F_Files for INs\SST\E50\E50.2\D2\','F:\Final F_Files for INs\SST\E50\E50.2\D2\'},0,'new',2800);
% save(%saveDir,varlist);


curr=6;
[mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
    mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
    mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
    mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
    mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
    GeneralInterneuronTest(4,4,'E50.2D2',...
    {'160421_000_001__XC_1_roibyhand_F.mat','160421_000_001__XC_2_roibyhand_F.mat',...
    '160421_000_001__XC_3_roibyhand_F.mat','160421_000_001__XC_4_roibyhand_F.mat'},...
    {'F:\Final F_Files for INs\SST\E50\E50.2\D3\','F:\Final F_Files for INs\SST\E50\E50.2\D3\',...
    'F:\Final F_Files for INs\SST\E50\E50.2\D3\','F:\Final F_Files for INs\SST\E50\E50.2\D3\'},0,'new',1400);

curr=7;
[mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
    mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
    mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
    mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
    mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
    GeneralInterneuronTest(4,4,'E50.2D3',...
    {'160422_000_001__XC_1_roibyhand_F.mat','160422_000_001__XC_2_roibyhand_F.mat',...
    '160422_000_001__XC_3_roibyhand_F.mat','160422_000_001__XC_4_roibyhand_F.mat'},...
    {'F:\Final F_Files for INs\SST\E50\E50.2\D4\','F:\Final F_Files for INs\SST\E50\E50.2\D4\',...
    'F:\Final F_Files for INs\SST\E50\E50.2\D4\','F:\Final F_Files for INs\SST\E50\E50.2\D4\'},0,'new',1400);
% save(%saveDir,varlist);


curr=8;
[mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
    mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
    mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
    mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
    mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
    GeneralInterneuronTest(4,4,'E50.2D4',...
    {'160424_000_001__XC_1_roibyhand_F.mat','160424_000_001__XC_2_roibyhand_F.mat',...
    '160424_000_001__XC_3_roibyhand_F.mat','160424_000_001__XC_4_roibyhand_F.mat'},...
    {'F:\Final F_Files for INs\SST\E50\E50.2\D5\','F:\Final F_Files for INs\SST\E50\E50.2\D5\',...
    'F:\Final F_Files for INs\SST\E50\E50.2\D5\','F:\Final F_Files for INs\SST\E50\E50.2\D5\'},0,'new',1400);
save(saveDir,varlist);


% 
% E32.3
m=2;
curr=9;
[mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
    mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
    mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
    mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
    mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
    GeneralInterneuronTest(4,4,'E32.3D1',...
    {'1222_000_000__XC_1_roibyhand_F.mat','1222_000_000__XC_2_roibyhand_F.mat',...
    '1222_000_000__XC_3_roibyhand_F.mat','1222_000_000__XC_4_roibyhand_F.mat'},...
    {'F:\Final F_Files for INs\SST\E32\E32.3\D1\','F:\Final F_Files for INs\SST\E32\E32.3\D1\',...
    'F:\Final F_Files for INs\SST\E32\E32.3\D1\','F:\Final F_Files for INs\SST\E32\E32.3\D1\'},1,'old');
% save(%saveDir,varlist);


curr=10;
[mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
    mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
    mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
    mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
    mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
    GeneralInterneuronTest(4,4,'E32.3D2',...
    {'1223_000_001__XC_1_roibyhand_F.mat','1223_000_001__XC_2_roibyhand_F.mat',...
    '1223_000_001__XC_3_roibyhand_F.mat','1223_000_001__XC_4_roibyhand_F.mat'},...
    {'F:\Final F_Files for INs\SST\E32\E32.3\D2\','F:\Final F_Files for INs\SST\E32\E32.3\D2\',...
    'F:\Final F_Files for INs\SST\E32\E32.3\D2\','F:\Final F_Files for INs\SST\E32\E32.3\D2\'},1,'old');
save(saveDir,varlist);


curr=11;
[mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
    mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
    mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
    mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
    mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
    GeneralInterneuronTest(4,4,'E32.3D3',...
    {'1224_000_000__XC_1_roibyhand_F.mat','1224_000_000__XC_2_roibyhand_F.mat',...
    '1224_000_000__XC_3_roibyhand_F.mat','1224_000_000__XC_4_roibyhand_F.mat'},...
    {'F:\Final F_Files for INs\SST\E32\E32.3\D3\','F:\Final F_Files for INs\SST\E32\E32.3\D3\',...
    'F:\Final F_Files for INs\SST\E32\E32.3\D3\','F:\Final F_Files for INs\SST\E32\E32.3\D3\'},1,'old');
%save(%saveDir,varlist);


curr=12;
[mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
    mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
    mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
    mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
    mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
    GeneralInterneuronTest(4,4,'E32.3D4',...
    {'1228_000_000__XC_1_roibyhand_F.mat','1228_000_000__XC_2_roibyhand_F.mat',...
    '1228_000_000__XC_3_roibyhand_F.mat','1228_000_000__XC_4_roibyhand_F.mat'},...
    {'F:\Final F_Files for INs\SST\E32\E32.3\D4\','F:\Final F_Files for INs\SST\E32\E32.3\D4\',...
    'F:\Final F_Files for INs\SST\E32\E32.3\D4\','F:\Final F_Files for INs\SST\E32\E32.3\D4\'},1,'old');
%save(%saveDir,varlist);


curr=13;
[mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
    mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
    mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
    mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr},...
    mouse(m).mfballout{curr},mouse(m).mtballout{curr},mouse(m).mtaballout{curr},mouse(m).mvrout{curr},mouse(m).mvraout{curr},mouse(m).mPRTAout{curr},mouse(m).reportfigs{curr},mouse(m).dFcorr{curr}]=...
    GeneralInterneuronTest(4,4,'E32.3D5',...
    {'1229_000_001__XC_1_roibyhand_F.mat','1229_000_001__XC_2_roibyhand_F.mat',...
    '1229_000_001__XC_3_roibyhand_F.mat','1229_000_001__XC_4_roibyhand_F.mat'},...
    {'F:\Final F_Files for INs\SST\E32\E32.3\D5\','F:\Final F_Files for INs\SST\E32\E32.3\D5\',...
    'F:\Final F_Files for INs\SST\E32\E32.3\D5\','F:\Final F_Files for INs\SST\E32\E32.3\D5\'},1,'old');

save(saveDir,varlist);



%save('F:\MA Data\InterneuronsLowerCheck\SSTinfo.mat','mouse');
% plot_SST_figs

% for p=1:4
%     [names{p},paths{p}]=uigetfile('*.mat','pick your files');
%     names{p}
%     paths{p}
% end
%%
% 
% 
% 
% 
% 
% 
% % 
% 
% % %%
% for p=1:4
%     [names{p},paths{p}]=uigetfile('*.mat','pick your files');
%     names{p}
%     paths{p}
% end
% 
% % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
% %     GeneralInterneuronTest(100,1,'X14.100SSTbyhand',...
% %     {'160208_000_002_hmm1_roibyhand_F.mat'},...
% %     {'F:\Interneron Videos\100hz\'});
% % 
% % %% SST No VR
% % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
% %     GeneralInterneuronTest(4,4,'X14.5D1',...
% %     {'1228_000_002_hmm1_roibyhand_F.mat','1228_000_002_hmm2_roibyhand_F.mat',...
% %     '1228_000_002_hmm3_roibyhand_F.mat','1228_000_002_hmm4_roibyhand_F.mat'},...
% %     {'F:\Interneron Videos\X14.5\151228\','F:\Interneron Videos\X14.5\151228\',...
% %     'F:\Interneron Videos\X14.5\151228\','F:\Interneron Videos\X14.5\151228\'},1);
% % 
% % 
% % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
% %     GeneralInterneuronTest(4,4,'X14.5D2',...
% %     {'1229_000_002_hmm1_roibyhand_F.mat','1229_000_002_hmm2_roibyhand_F.mat',...
% %     '1229_000_002_hmm3_roibyhand_F.mat','1229_000_002_hmm4_roibyhand_F.mat'},...
% %     {'F:\Interneron Videos\X14.5\151229\','F:\Interneron Videos\X14.5\151229\',...
% %     'F:\Interneron Videos\X14.5\151229\','F:\Interneron Videos\X14.5\151229\'},1);
% 
% % % X14.3
% % 
% % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
% %     GeneralInterneuronTest(4,4,'X14.3D1',...
% %     {'160114_000_002_FFT_1_roibyhand_F.mat','160114_000_002_FFT_2_roibyhand_F.mat',...
% %     '160114_000_002_FFT_3_roibyhand_F.mat','160114_000_002_FFT_4_roibyhand_F.mat'},...
% %     {'E:\2016\X14.3\160114\','E:\2016\X14.3\160114\',...
% %     'E:\2016\X14.3\160114\','E:\2016\X14.3\160114\'},1);
%  
% % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
% %     GeneralInterneuronTest(4,4,'X14.3D2',...
% %     {'160115_000_002_FFT_1_roibyhand_F.mat','160115_000_002_FFT_2_roibyhand_F.mat',...
% %     '160115_000_002_FFT_3_roibyhand_F.mat','160115_000_002_FFT_4_roibyhand_F.mat'},...
% %     {'E:\2016\X14.3\160115\','E:\2016\X14.3\160115\',...
% %     'E:\2016\X14.3\160115\','E:\2016\X14.3\160115\'});
% % 
% % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
% %     GeneralInterneuronTest(4,4,'X14.3D3',...
% %     {'160118_000_004_FFT_1_roibyhand_F.mat','160118_000_004_FFT_2_roibyhand_F.mat',...
% %     '160118_000_004_FFT_3_roibyhand_F.mat','160118_000_004_FFT_4_roibyhand_F.mat'},...
% %     {'E:\2016\X14.3\160118\','E:\2016\X14.3\160118\',...
% %     'E:\2016\X14.3\160118\','E:\2016\X14.3\160118\'});
% % 
% % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
% %     GeneralInterneuronTest(4,4,'X14.3D4',...
% %     {'160119_000_004_FFT_1_roibyhand_F.mat','160119_000_004_FFT_2_roibyhand_F.mat',...
% %     '160119_000_004_FFT_3_roibyhand_F.mat','160119_000_004_FFT_4_roibyhand_F.mat'},...
% %     {'E:\2016\X14.3\160119\','E:\2016\X14.3\160119\',...
% %     'E:\2016\X14.3\160119\','E:\2016\X14.3\160119\'});
% % 
% % 
% % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
% %     GeneralInterneuronTest(4,4,'X14.3D5',...
% %     {'160120_000_004_FFT_1_roibyhand_F.mat','160120_000_004_FFT_2_roibyhand_F.mat',...
% %     '160120_000_004_FFT_3_roibyhand_F.mat','160120_000_004_FFT_4_roibyhand_F.mat'},...
% %     {'E:\2016\X14.3\160120\','E:\2016\X14.3\160120\',...
% %     'E:\2016\X14.3\160120\','E:\2016\X14.3\160120\'},1);
% % % 
% % 
% % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
% %     GeneralInterneuronTest(4,4,'X14.3D6',...
% %     {'160121_000_003_FFT_1_roibyhand_F.mat','160121_000_003_FFT_2_roibyhand_F.mat',...
% %     '160121_000_003_FFT_3_roibyhand_F.mat','160121_000_003_FFT_4_roibyhand_F.mat'},...
% %     {'E:\2016\X14.3\160121\','E:\2016\X14.3\160121\',...
% %     'E:\2016\X14.3\160121\','E:\2016\X14.3\160121\'},1);
% % 
% % 
% % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
% %     GeneralInterneuronTest(4,4,'X14.3D7',...
% %     {'160122_000_016_hmm1_roibyhand_F.mat','160122_000_016_hmm2_roibyhand_F.mat',...
% %     '160122_000_016_hmm3_roibyhand_F.mat','160122_000_016_hmm4_roibyhand_F.mat'},...
% %     {'E:\2016\X14.3\160122\','E:\2016\X14.3\160122\',...
% %     'E:\2016\X14.3\160122\','E:\2016\X14.3\160122\'},1);
% 
% % %X14.1
% 
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
%     GeneralInterneuronTest(4,4,'X14.1D1',...
%     {'1202_000_000_FFT_1_roibyhand_F.mat','1202_000_000_FFT_2_roibyhand_F.mat',...
%     '1202_000_000_FFT_3_roibyhand_F.mat','1202_000_000_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\X14.1\151202\','F:\Interneron Videos\X14.1\151202\',...
%     'F:\Interneron Videos\X14.1\151202\','F:\Interneron Videos\X14.1\151202\'},1);
% 
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr}, mouse(m).Corrswoez{curr}]=...
%     GeneralInterneuronTest(4,4,'X14.1D2',...
%     {'1203_000_003_FFT_1_roibyhand_F.mat','1203_000_003_FFT_2_roibyhand_F.mat',...
%     '1203_000_003_FFT_3_roibyhand_F.mat','1203_000_003_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\X14.1\151203\','F:\Interneron Videos\X14.1\151203\',...
%     'F:\Interneron Videos\X14.1\151203\','F:\Interneron Videos\X14.1\151203\'},1);
% 
% [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
%     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
%     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
%     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
%     GeneralInterneuronTest(4,4,'X14.1D3',...
%     {'1204_000_002_FFT_1_roibyhand_F.mat','1204_000_002_FFT_2_roibyhand_F.mat',...
%     '1204_000_002_FFT_3_roibyhand_F.mat','1204_000_002_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\X14.1\151204\','F:\Interneron Videos\X14.1\151204\',...
%     'F:\Interneron Videos\X14.1\151204\','F:\Interneron Videos\X14.1\151204\'},1);
% 
% [mouse(m).Falls{18},mouse(m).Rotations{18},mouse(m).Forwards{18},...
%     mouse(m).Corrs{18},mouse(m).Dists{18},mouse(m).CPP{18},mouse(m).ybinned{18},...
%     mouse(m).rewards{18},mouse(m).F0{18},mouse(m).F08{18},mouse(m).DistsRun{18},...
%     mouse(m).CorrsRun{18},mouse(m).Distswoez{18},mouse(m).Corrswoez{18}]=...
%     GeneralInterneuronTest(4,4,'X14.1D4',...
%     {'1205_000_001_FFT_1_roibyhand_F.mat','1205_000_001_FFT_2_roibyhand_F.mat',...
%     '1205_000_001_FFT_3_roibyhand_F.mat','1205_000_001_FFT_4_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\X14.1\151205\','F:\Interneron Videos\X14.1\151205\',...
%     'F:\Interneron Videos\X14.1\151205\','F:\Interneron Videos\X14.1\151205\'},1);
% 
% [mouse(m).Falls{19},mouse(m).Rotations{19},mouse(m).Forwards{19},...
%     mouse(m).Corrs{19},mouse(m).Dists{19},mouse(m).CPP{19},mouse(m).ybinned{19},...
%     mouse(m).rewards{19},mouse(m).F0{19},mouse(m).F08{19},mouse(m).DistsRun{19},...
%     mouse(m).CorrsRun{19},mouse(m).Distswoez{19},mouse(m).Corrswoez{19}]=...
%     GeneralInterneuronTest(4,4,'X14.1D5',...
%     {'1208_000_001_FFT_1_roibyhand_F.mat','1208_000_001_FFT_1_roibyhand_F.mat',...
%     '1208_000_001_FFT_1_roibyhand_F.mat','1208_000_001_FFT_1_roibyhand_F.mat'},...
%     {'F:\Interneron Videos\X14.1\151208\','F:\Interneron Videos\X14.1\151208\',...
%     'F:\Interneron Videos\X14.1\151208\','F:\Interneron Videos\X14.1\151208\'},1);
% % 
% % 
% % 
% % % X14.2
% % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
% %     GeneralInterneuronTest(4,4,'X14.2D1',...
% %     {'1214_000_001_hmm1_roibyhand_F.mat','1214_000_001_hmm2_roibyhand_F.mat',...
% %     '1214_000_001_hmm3_roibyhand_F.mat','1214_000_001_hmm4_roibyhand_F.mat'},...
% %     {'E:\2016\X14.2\151214\','E:\2016\X14.2\151214\',...
% %     'E:\2016\X14.2\151214\','E:\2016\X14.2\151214\'},1);
% % 
% % 
% % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
% %     GeneralInterneuronTest(4,4,'X14.2D2',...
% %     {'1215_000_003_hmm1_roibyhand_F.mat','1215_000_003_hmm2_roibyhand_F.mat',...
% %     '1215_000_003_hmm3_roibyhand_F.mat','1215_000_003_hmm4_roibyhand_F.mat'},...
% %     {'E:\2016\X14.2\151215\','E:\2016\X14.2\151215\',...
% %     'E:\2016\X14.2\151215\','E:\2016\X14.2\151215\'});
% % 
% % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
% %     GeneralInterneuronTest(4,4,'X14.2D3',...
% %     {'1216_000_003_hmm1_roibyhand_F.mat','1216_000_003_hmm2_roibyhand_F.mat',...
% %     '1216_000_003_hmm3_roibyhand_F.mat','1216_000_003_hmm4_roibyhand_F.mat'},...
% %     {'E:\2016\X14.2\151216\','E:\2016\X14.2\151216\',...
% %     'E:\2016\X14.2\151216\','E:\2016\X14.2\151216\'});
% % 
% % [mouse(m).Falls{curr},mouse(m).Rotations{curr},mouse(m).Forwards{curr},...
% %     mouse(m).Corrs{curr},mouse(m).Dists{curr},mouse(m).CPP{curr},mouse(m).ybinned{curr},...
% %     mouse(m).rewards{curr},mouse(m).F0{curr},mouse(m).F08{curr},mouse(m).DistsRun{curr},...
% %     mouse(m).CorrsRun{curr},mouse(m).Distswoez{curr},mouse(m).Corrswoez{curr}]=...
% %     GeneralInterneuronTest(4,4,'X14.2D4',...
% %     {'1217_000_003_hmm1_roibyhand_F.mat','1217_000_003_hmm2_roibyhand_F.mat',...
% %     '1217_000_003_hmm3_roibyhand_F.mat','1217_000_003_hmm4_roibyhand_F.mat'},...
% %     {'E:\2016\X14.2\151217\','E:\2016\X14.2\151217\',...
% %     'E:\2016\X14.2\151217\','E:\2016\X14.2\151217\'},1);
% % 
% 
% % DAY 5 is not F_POLYED
% 
